name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  v3i:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh v3i
  x86-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-linux
  x86-linux-o2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-linux -O2
  x86-linux-o3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-linux -O3
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-64-linux
  x86_64-linux-o2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-64-linux -O2
  x86_64-linux-o3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh x86-64-linux -O3
  jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/build-test.sh jvm

